- hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: ubuntu
  gather_facts: false
  vars:
    phps:
      - wp-cli/wp-cli
    npms:
      - gulp-cli
    gems:
      - swiftly
      - trio
    pip2:
      - neovim
      - powerline-status
    pip3:
      - awscli
      - dopy
      - httpie-unixsocket
      - httpie
      - neovim
      - neovim-remote
  tasks:
    - name: install composer packs {{ phps }}
      composer:
        command: require
        global_command: yes
        arguments: "{{ item }}"
      with_items: "{{ phps }}"
    - name: install npm packages {{ npms }}
      npm:
        name: "{{ item }}"
        state: present
        path: ~/.npm
        global: yes
      with_items: "{{ npms }}"
    - name: install ruby gems {{ gems }}
      gem:
        name: "{{ item }}"
        user_install: yes
      with_items: "{{ gems }}"
    - name: install pip2 packs {{ pip2 }}
      pip:
        extra_args: --user
        name: "{{ pip2 }}"
    - name: install pip3 packs {{ pip3 }}
      pip:
        executable: pip3
        extra_args: --user
        name: "{{ pip3 }}"
